name: SlimyTreeTaps
version: ${project.version}
author: TheBusyBiscuit
description: Adds tree tapping, rubber, and an alternative plastic production route for Slimefun Legacy.
website: https://github.com/wickidcow/SF_SlimyTreeTaps

main: io.github.thebusybiscuit.slimytreetaps.TreeTaps
depend: [Slimefun]

api-version: '26.2'
folia-supported: true
