blank_issues_enabled: false
contact_links:
  - name: Slimefun Legacy
    url: https://github.com/wickidcow/Slimefun-Legacy
    about: Check the Slimefun Legacy project for core Slimefun information and compatibility notes.
